name: "Setup Probitas"
description: "Setup Probitas by installing Probitas CLI and adding it to the path."
author: "JSR Probitas"
branding:
  icon: "check-circle"
  color: "green"

inputs:
  probitas-version:
    description: "The Probitas version to install. Can be a semver version or 'latest'."
    default: "latest"

outputs:
  probitas-version:
    description: "The Probitas version that was installed."
    value: ${{ steps.verify-probitas.outputs.probitas-version }}

runs:
  using: "composite"
  steps:
    - name: Install Probitas CLI
      id: install-probitas
      shell: bash
      env:
        PROBITAS_VERSION: ${{ inputs.probitas-version != 'latest' && inputs.probitas-version || '' }}
        PROBITAS_INSTALL_DIR: ${{ runner.temp }}/probitas-bin
      run: |
        echo "Installing Probitas CLI${PROBITAS_VERSION:+ version $PROBITAS_VERSION}..."
        curl -fsSL https://raw.githubusercontent.com/jsr-probitas/cli/main/install.sh | bash

        # Add to PATH
        echo "$PROBITAS_INSTALL_DIR" >> $GITHUB_PATH

    - name: Verify Probitas
      id: verify-probitas
      shell: bash
      env:
        PROBITAS_INSTALL_DIR: ${{ runner.temp }}/probitas-bin
      run: |
        # Verify installation
        if ! "$PROBITAS_INSTALL_DIR/probitas" --version &> /dev/null; then
          echo "Error: Probitas CLI installation failed"
          exit 1
        fi

        # Get installed version
        INSTALLED_VERSION=$("$PROBITAS_INSTALL_DIR/probitas" --version 2>&1 | head -n 1)
        echo "Installed: $INSTALLED_VERSION"
        echo "probitas-version=$INSTALLED_VERSION" >> $GITHUB_OUTPUT
